name: vrchat_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/GizmoOAO/vrchat_dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  json_annotation: ^3.1.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.14.4
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
